import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Nabar from "./components/Nabar";
import prisma from "./lib/db";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import {unstable_noStore as noStore} from 'next/cache'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
async function getData(userId:string){
  noStore()
  if(userId){
      const data=await prisma.user.findUnique({
    where:{
      id:userId,
    },
    select:{
      colorSchema:true
    }
  })
    return data
  }

}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {getUser}=getKindeServerSession();
  const user=await getUser()
  const data =await getData(user?.id as string)
  return (
    <html lang="en">
      <body className={`${data?.colorSchema ?? "theme-violet"}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Nabar/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
